### ISSUE TITLE
It's Probably Not You But Sure As Hell Ruined my Yester Night and Day Today including Work

### ISSUE THREAD

**Issue by wilburlikesmith** [Jack-Myth/Threshold-Miku-Customizer-2#1]
Got this via Windows Store App 

Threshold Miku Customizer 2.exe

Not entirely sure what, it definitely jacked my CPU and disarmed my Firewall and Defender and well my whole bloody Setup. The rescue as in retrospect useless because I'm still finding brokeness here and there... 

Not blaming you, also I could be wrong... If you'd like I can upload the file zipped.

Footnote: Now off to Windows Store to report...

**Comment by Jack-Myth** [comment]
I haven't published it on Windows Store. You can paste the windows store address here.
